[2024-02-27 22:43:49,600: INFO: stage_03_training_model: >>>>>> stage Training Model started <<<<<<]
[2024-02-27 22:43:49,600: ERROR: stage_03_training_model: [Errno 2] No such file or directory: 'config/config.yaml']
Traceback (most recent call last):
  File "stage_03_training_model.py", line 31, in <module>
    obj.main()
  File "stage_03_training_model.py", line 13, in main
    config = ConfigurationManager()
  File "/Users/rokaspranevicius/Documents/GitHub/Muffin-vs-Chihuahua-Classification/src/cnnClassifier/config/configuration.py", line 16, in __init__
    self.config = read_yaml(config_filepath)
  File "/Users/rokaspranevicius/miniforge3/envs/muffin/lib/python3.8/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/Users/rokaspranevicius/Documents/GitHub/Muffin-vs-Chihuahua-Classification/src/cnnClassifier/utils/common.py", line 37, in read_yaml
    raise e
  File "/Users/rokaspranevicius/Documents/GitHub/Muffin-vs-Chihuahua-Classification/src/cnnClassifier/utils/common.py", line 30, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
